name = "exam-system"
main = "src/index.js"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "exam"
database_id = "700d1c2e-1e21-4bdb-a0f9-6693b1e1a743"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "exam"
