name = "exam-system"
main = "src/index.js"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "exam"
database_id = "014fb844-bc51-4b66-850a-0a2a04e4506b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "exam"
